// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "kredit-plus/domain"

	mock "github.com/stretchr/testify/mock"
)

// CustomerRepository is an autogenerated mock type for the CustomerRepository type
type CustomerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, customerInput
func (_m *CustomerRepository) Create(ctx context.Context, customerInput *domain.Customer) (*domain.Customer, error) {
	ret := _m.Called(ctx, customerInput)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Customer) (*domain.Customer, error)); ok {
		return rf(ctx, customerInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Customer) *domain.Customer); ok {
		r0 = rf(ctx, customerInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Customer) error); ok {
		r1 = rf(ctx, customerInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchAll provides a mock function with given fields: ctx
func (_m *CustomerRepository) FetchAll(ctx context.Context) ([]domain.Customer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 []domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Customer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Customer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: ctx, customerID
func (_m *CustomerRepository) FetchByID(ctx context.Context, customerID uint) (domain.Customer, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (domain.Customer, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) domain.Customer); ok {
		r0 = rf(ctx, customerID)
	} else {
		r0 = ret.Get(0).(domain.Customer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, customerInput
func (_m *CustomerRepository) Update(ctx context.Context, customerInput *domain.Customer) (*domain.Customer, error) {
	ret := _m.Called(ctx, customerInput)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Customer) (*domain.Customer, error)); ok {
		return rf(ctx, customerInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Customer) *domain.Customer); ok {
		r0 = rf(ctx, customerInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Customer) error); ok {
		r1 = rf(ctx, customerInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerRepository creates a new instance of CustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerRepository {
	mock := &CustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
