// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "kredit-plus/domain"

	mock "github.com/stretchr/testify/mock"
)

// CustomerTenorUsecase is an autogenerated mock type for the CustomerTenorUsecase type
type CustomerTenorUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, reqBody
func (_m *CustomerTenorUsecase) Create(ctx context.Context, reqBody *domain.CustomerTenorCreateRequest) (*domain.CustomerTenor, error) {
	ret := _m.Called(ctx, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.CustomerTenor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerTenorCreateRequest) (*domain.CustomerTenor, error)); ok {
		return rf(ctx, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerTenorCreateRequest) *domain.CustomerTenor); ok {
		r0 = rf(ctx, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CustomerTenor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CustomerTenorCreateRequest) error); ok {
		r1 = rf(ctx, reqBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, customerTenorID
func (_m *CustomerTenorUsecase) Delete(ctx context.Context, customerTenorID uint) error {
	ret := _m.Called(ctx, customerTenorID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, customerTenorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAll provides a mock function with given fields: ctx
func (_m *CustomerTenorUsecase) FetchAll(ctx context.Context) ([]domain.CustomerTenor, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 []domain.CustomerTenor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.CustomerTenor, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.CustomerTenor); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CustomerTenor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: ctx, customerTenorID
func (_m *CustomerTenorUsecase) FetchByID(ctx context.Context, customerTenorID uint) (domain.CustomerTenor, error) {
	ret := _m.Called(ctx, customerTenorID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.CustomerTenor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (domain.CustomerTenor, error)); ok {
		return rf(ctx, customerTenorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) domain.CustomerTenor); ok {
		r0 = rf(ctx, customerTenorID)
	} else {
		r0 = ret.Get(0).(domain.CustomerTenor)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, customerTenorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, reqBody, customerTenorID
func (_m *CustomerTenorUsecase) Update(ctx context.Context, reqBody *domain.CustomerTenorUpdateRequest, customerTenorID uint) (*domain.CustomerTenor, error) {
	ret := _m.Called(ctx, reqBody, customerTenorID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.CustomerTenor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerTenorUpdateRequest, uint) (*domain.CustomerTenor, error)); ok {
		return rf(ctx, reqBody, customerTenorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerTenorUpdateRequest, uint) *domain.CustomerTenor); ok {
		r0 = rf(ctx, reqBody, customerTenorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CustomerTenor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CustomerTenorUpdateRequest, uint) error); ok {
		r1 = rf(ctx, reqBody, customerTenorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerTenorUsecase creates a new instance of CustomerTenorUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerTenorUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerTenorUsecase {
	mock := &CustomerTenorUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
