// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "kredit-plus/domain"

	mock "github.com/stretchr/testify/mock"
)

// TransactionUsecase is an autogenerated mock type for the TransactionUsecase type
type TransactionUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, reqBody
func (_m *TransactionUsecase) Create(ctx context.Context, reqBody *domain.TransactionCreateRequest) (*domain.Transaction, error) {
	ret := _m.Called(ctx, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransactionCreateRequest) (*domain.Transaction, error)); ok {
		return rf(ctx, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransactionCreateRequest) *domain.Transaction); ok {
		r0 = rf(ctx, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.TransactionCreateRequest) error); ok {
		r1 = rf(ctx, reqBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchAll provides a mock function with given fields: ctx
func (_m *TransactionUsecase) FetchAll(ctx context.Context) ([]domain.Transaction, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 []domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Transaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: ctx, transactionID
func (_m *TransactionUsecase) FetchByID(ctx context.Context, transactionID uint) (domain.Transaction, error) {
	ret := _m.Called(ctx, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (domain.Transaction, error)); ok {
		return rf(ctx, transactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) domain.Transaction); ok {
		r0 = rf(ctx, transactionID)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, reqBody, transactionID
func (_m *TransactionUsecase) Update(ctx context.Context, reqBody *domain.TransactionUpdateRequest, transactionID uint) (*domain.Transaction, error) {
	ret := _m.Called(ctx, reqBody, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransactionUpdateRequest, uint) (*domain.Transaction, error)); ok {
		return rf(ctx, reqBody, transactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransactionUpdateRequest, uint) *domain.Transaction); ok {
		r0 = rf(ctx, reqBody, transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.TransactionUpdateRequest, uint) error); ok {
		r1 = rf(ctx, reqBody, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionUsecase creates a new instance of TransactionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionUsecase {
	mock := &TransactionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
